cars=[]
bikes=[]
vehicles=[]
myNum=[2,4,6,8,1,3,7,9,5]
print("MyNum :  ",myNum,"\n")
myNum.sort();
print("MyNum[sorted] :  ",myNum,"\n")
myNum.reverse()
print("MyNum[reversed] :  ",myNum,"\n")
cars.append("Audi")
cars.append("Lamborghini")
cars.append("Bugatti")
cars.append("Porshce")
bikes.append("Kawasaki")
bikes.append("Ducatti")
bikes.append("Suzuki")
bikes.append("Honda")
c=cars.copy()
print(cars,"\n")
#print("Bikes : ",bikes,"\n")
cars.insert(2,"Koenigsegg")
print(cars,"\n")
cars.remove("Audi")
print(cars,"\n")
print("Popped item :  ",cars.pop(),"\n")
#print("Count :  ",cars.len())
#print(cars.count("Audi"))
print(cars,"\n")
print("Koengisegg at index :  ",cars.index("Koenigsegg"),"\n")
cars.append("Koenigsegg")
print(cars,"\n")
print("Koenigsegg count :  ",cars.count("Koenigsegg"),"\n")
print("Koenigsegg at index after 1 : ",cars.index("Koenigsegg",2,5),"\n")
vehicles.extend(bikes)
vehicles.extend(cars)
print("Vehicles : ",vehicles,"\n")
vehicles.sort()
print("Vehicles[Sorted] : ",vehicles,"\n")
vehicles.clear()
print("Vehicles : ",vehicles,"\n")
print("Cars : ",end=' ')
for car in cars:
    print(car,end=' ')
print("\n\nInitial Cars :  ",c,"\n")
